---
- hosts: testsystemd 
  become: true
  tasks:
  - name: copy watchlog
    copy:
      src: files/test_systemd/watchlog
      dest: /etc/sysconfig/
      owner: root
      group: root
      mode: 0644

  - name: copy watchlog.log
    copy:
      src: files/test_systemd/watchlog.log
      dest: /var/log/
      owner: root
      group: root
      mode: 0666

  - name: copy watchlog.sh
    copy:
      src: files/test_systemd/watchlog.sh
      dest: /opt/
      owner: root
      group: root
      mode: 0755


  - name: copy watchlog.service
    copy:
      src: files/test_systemd/watchlog.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644

  - name: copy watchlog.timer
    copy:
      src: files/test_systemd/watchlog.timer
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644

  - name: starting service watchlog
    shell: systemctl start watchlog.timer watchlog.service

  - name: install the latest version of spawn-fcgi
    shell: yum install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd -y

  - name: change /etc/sysconfig/spawn-fcgi
    shell: sed -i 's/#SOCKET/SOCKET/' /etc/sysconfig/spawn-fcgi && sed -i 's/#OPTIONS/OPTIONS/' /etc/sysconfig/spawn-fcgi

  - name: copy spawn-fcgi unit file
    copy:
      src: files/test_systemd/spawn-fcgi.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644

  - name: starting spawn-fcgi service
    shell: systemctl start spawn-fcgi.service

  - name: start spawn-fcgi service and get status
    shell: systemctl start spawn-fcgi.service && systemctl status spawn-fcgi.service

  - name: copy /usr/lib/systemd/system/httpd.service to /etc/systemd/system/httpd@.service
    shell: cp /usr/lib/systemd/system/httpd.service /etc/systemd/system/httpd@.service

  - name: change /etc/systemd/system/httpd@.service
    shell: sed -i 's/EnvironmentFile=\/etc\/sysconfig\/httpd/EnvironmentFile=\/etc\/sysconfig\/httpd-%I/' /etc/systemd/system/httpd@.service

  - name: copy /etc/sysconfig/httpd-first
    copy:
      src: files/test_systemd/httpd-first
      dest:  /etc/sysconfig/
      owner: root
      group: root
      mode: 0644

  - name: copy /etc/sysconfig/httpd-second
    copy:
      src: files/test_systemd/httpd-second
      dest:  /etc/sysconfig/
      owner: root
      group: root
      mode: 0644

  - name: copy httpd config to first and second
    shell: cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/first.conf && cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/second.conf

  - name: edit httpd second conf
    shell: sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/second.conf && sed -i 's/PidFile/PidFile \/var\/run\/httpd-second.pid/' /etc/httpd/conf/second.conf && sed -i 's/# least PidFile/PidFile/' /etc/httpd/conf/second.conf

  - name: stop httpd service and reload systemd manager configuration
    shell: systemctl stop httpd && systemctl daemon-reload

  - name: Start httpd-first and httpd-second
    shell: systemctl start httpd@first && systemctl start httpd@second