---
# tasks file for zabbix-agent
- name: zabbix-agent | install zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm

- name: zabbix-agent | install zabbix-agent
  yum:
    name: zabbix-agent
    state: present

- name: zabbix-agent | copy config
  copy:
    src: zabbix_agentd.conf
    dest: /etc/zabbix_agentd.conf
    backup: yes
    mode: 0644
    owner: root
    group: root

- name: zabbix-agent | start and enable zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
